// +build !ignore_autogenerated

/*
Copyright 2017 The helm-apiserver Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	helm "github.com/bitnami-labs/helm-apiserver/pkg/apis/helm"
	v1 "k8s.io/api/authorization/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec,
		Convert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec,
		Convert_v1alpha1_Release_To_helm_Release,
		Convert_helm_Release_To_v1alpha1_Release,
		Convert_v1alpha1_ReleaseList_To_helm_ReleaseList,
		Convert_helm_ReleaseList_To_v1alpha1_ReleaseList,
		Convert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec,
		Convert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec,
		Convert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus,
		Convert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus,
		Convert_v1alpha1_ReleaseStatusStrategy_To_helm_ReleaseStatusStrategy,
		Convert_helm_ReleaseStatusStrategy_To_v1alpha1_ReleaseStatusStrategy,
		Convert_v1alpha1_ReleaseStrategy_To_helm_ReleaseStrategy,
		Convert_helm_ReleaseStrategy_To_v1alpha1_ReleaseStrategy,
	)
}

func autoConvert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec(in *ImpersonateSpec, out *helm.ImpersonateSpec, s conversion.Scope) error {
	out.User = in.User
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]v1.ExtraValue)(unsafe.Pointer(&in.Extra))
	out.ServiceAccountName = in.ServiceAccountName
	return nil
}

// Convert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec(in *ImpersonateSpec, out *helm.ImpersonateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec(in, out, s)
}

func autoConvert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec(in *helm.ImpersonateSpec, out *ImpersonateSpec, s conversion.Scope) error {
	out.User = in.User
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]v1.ExtraValue)(unsafe.Pointer(&in.Extra))
	out.ServiceAccountName = in.ServiceAccountName
	return nil
}

// Convert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec is an autogenerated conversion function.
func Convert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec(in *helm.ImpersonateSpec, out *ImpersonateSpec, s conversion.Scope) error {
	return autoConvert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec(in, out, s)
}

func autoConvert_v1alpha1_Release_To_helm_Release(in *Release, out *helm.Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Release_To_helm_Release is an autogenerated conversion function.
func Convert_v1alpha1_Release_To_helm_Release(in *Release, out *helm.Release, s conversion.Scope) error {
	return autoConvert_v1alpha1_Release_To_helm_Release(in, out, s)
}

func autoConvert_helm_Release_To_v1alpha1_Release(in *helm.Release, out *Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_helm_Release_To_v1alpha1_Release is an autogenerated conversion function.
func Convert_helm_Release_To_v1alpha1_Release(in *helm.Release, out *Release, s conversion.Scope) error {
	return autoConvert_helm_Release_To_v1alpha1_Release(in, out, s)
}

func autoConvert_v1alpha1_ReleaseList_To_helm_ReleaseList(in *ReleaseList, out *helm.ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helm.Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReleaseList_To_helm_ReleaseList is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseList_To_helm_ReleaseList(in *ReleaseList, out *helm.ReleaseList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseList_To_helm_ReleaseList(in, out, s)
}

func autoConvert_helm_ReleaseList_To_v1alpha1_ReleaseList(in *helm.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_helm_ReleaseList_To_v1alpha1_ReleaseList is an autogenerated conversion function.
func Convert_helm_ReleaseList_To_v1alpha1_ReleaseList(in *helm.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	return autoConvert_helm_ReleaseList_To_v1alpha1_ReleaseList(in, out, s)
}

func autoConvert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec(in *ReleaseSpec, out *helm.ReleaseSpec, s conversion.Scope) error {
	out.RepoURL = in.RepoURL
	out.ChartName = in.ChartName
	out.Version = in.Version
	out.Values = in.Values
	if err := Convert_v1alpha1_ImpersonateSpec_To_helm_ImpersonateSpec(&in.Impersonate, &out.Impersonate, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec(in *ReleaseSpec, out *helm.ReleaseSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseSpec_To_helm_ReleaseSpec(in, out, s)
}

func autoConvert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *helm.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	out.RepoURL = in.RepoURL
	out.ChartName = in.ChartName
	out.Version = in.Version
	out.Values = in.Values
	if err := Convert_helm_ImpersonateSpec_To_v1alpha1_ImpersonateSpec(&in.Impersonate, &out.Impersonate, s); err != nil {
		return err
	}
	return nil
}

// Convert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec is an autogenerated conversion function.
func Convert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *helm.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return autoConvert_helm_ReleaseSpec_To_v1alpha1_ReleaseSpec(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus(in *ReleaseStatus, out *helm.ReleaseStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Notes = in.Notes
	return nil
}

// Convert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus(in *ReleaseStatus, out *helm.ReleaseStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStatus_To_helm_ReleaseStatus(in, out, s)
}

func autoConvert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *helm.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.Notes = in.Notes
	return nil
}

// Convert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus is an autogenerated conversion function.
func Convert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *helm.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	return autoConvert_helm_ReleaseStatus_To_v1alpha1_ReleaseStatus(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStatusStrategy_To_helm_ReleaseStatusStrategy(in *ReleaseStatusStrategy, out *helm.ReleaseStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_ReleaseStatusStrategy_To_helm_ReleaseStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStatusStrategy_To_helm_ReleaseStatusStrategy(in *ReleaseStatusStrategy, out *helm.ReleaseStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStatusStrategy_To_helm_ReleaseStatusStrategy(in, out, s)
}

func autoConvert_helm_ReleaseStatusStrategy_To_v1alpha1_ReleaseStatusStrategy(in *helm.ReleaseStatusStrategy, out *ReleaseStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_helm_ReleaseStatusStrategy_To_v1alpha1_ReleaseStatusStrategy is an autogenerated conversion function.
func Convert_helm_ReleaseStatusStrategy_To_v1alpha1_ReleaseStatusStrategy(in *helm.ReleaseStatusStrategy, out *ReleaseStatusStrategy, s conversion.Scope) error {
	return autoConvert_helm_ReleaseStatusStrategy_To_v1alpha1_ReleaseStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStrategy_To_helm_ReleaseStrategy(in *ReleaseStrategy, out *helm.ReleaseStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_ReleaseStrategy_To_helm_ReleaseStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStrategy_To_helm_ReleaseStrategy(in *ReleaseStrategy, out *helm.ReleaseStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStrategy_To_helm_ReleaseStrategy(in, out, s)
}

func autoConvert_helm_ReleaseStrategy_To_v1alpha1_ReleaseStrategy(in *helm.ReleaseStrategy, out *ReleaseStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_helm_ReleaseStrategy_To_v1alpha1_ReleaseStrategy is an autogenerated conversion function.
func Convert_helm_ReleaseStrategy_To_v1alpha1_ReleaseStrategy(in *helm.ReleaseStrategy, out *ReleaseStrategy, s conversion.Scope) error {
	return autoConvert_helm_ReleaseStrategy_To_v1alpha1_ReleaseStrategy(in, out, s)
}
